// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnr7vFiIH_qWO6Gb3R1r_muXK0YnBaXJM',
    appId: '1:346040128591:web:bb4392f5ea501923b2c63a',
    messagingSenderId: '346040128591',
    projectId: 'shopping-app-ee7c1',
    authDomain: 'shopping-app-ee7c1.firebaseapp.com',
    storageBucket: 'shopping-app-ee7c1.firebasestorage.app',
    measurementId: 'G-2HLMFMKZ84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwbpAW_jXcFW5Wqs0D0OeL3xRF3dwi9M',
    appId: '1:346040128591:android:b425222ddd05e863b2c63a',
    messagingSenderId: '346040128591',
    projectId: 'shopping-app-ee7c1',
    storageBucket: 'shopping-app-ee7c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKgTmk0dftcAc8-VdbVMzt_p1uKabVHk',
    appId: '1:346040128591:ios:f40add3d78a46f9db2c63a',
    messagingSenderId: '346040128591',
    projectId: 'shopping-app-ee7c1',
    storageBucket: 'shopping-app-ee7c1.firebasestorage.app',
    iosBundleId: 'com.arpit.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsKgTmk0dftcAc8-VdbVMzt_p1uKabVHk',
    appId: '1:346040128591:ios:f40add3d78a46f9db2c63a',
    messagingSenderId: '346040128591',
    projectId: 'shopping-app-ee7c1',
    storageBucket: 'shopping-app-ee7c1.firebasestorage.app',
    iosBundleId: 'com.arpit.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnr7vFiIH_qWO6Gb3R1r_muXK0YnBaXJM',
    appId: '1:346040128591:web:04fd52aca4683b27b2c63a',
    messagingSenderId: '346040128591',
    projectId: 'shopping-app-ee7c1',
    authDomain: 'shopping-app-ee7c1.firebaseapp.com',
    storageBucket: 'shopping-app-ee7c1.firebasestorage.app',
    measurementId: 'G-FWYZWDJCCD',
  );
}
